# coding: utf-8

"""
ME TT DataPortal Data Portal API

ME TT DataPortal Data Portal APIs to fetch Gut Microbes Genomes / Genes information.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class GeneDbcanAnnotationSchema(BaseModel):
    """
    dbCAN / CAZyme annotations.
    """  # noqa: E501

    prot_type: Optional[StrictStr] = None
    prot_family: Optional[List[StrictStr]] = None
    substrate_pul: Optional[StrictStr] = None
    substrate_sub: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "prot_type",
        "prot_family",
        "substrate_pul",
        "substrate_sub",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneDbcanAnnotationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if prot_type (nullable) is None
        # and model_fields_set contains the field
        if self.prot_type is None and "prot_type" in self.model_fields_set:
            _dict["prot_type"] = None

        # set to None if prot_family (nullable) is None
        # and model_fields_set contains the field
        if self.prot_family is None and "prot_family" in self.model_fields_set:
            _dict["prot_family"] = None

        # set to None if substrate_pul (nullable) is None
        # and model_fields_set contains the field
        if self.substrate_pul is None and "substrate_pul" in self.model_fields_set:
            _dict["substrate_pul"] = None

        # set to None if substrate_sub (nullable) is None
        # and model_fields_set contains the field
        if self.substrate_sub is None and "substrate_sub" in self.model_fields_set:
            _dict["substrate_sub"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneDbcanAnnotationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "prot_type": obj.get("prot_type"),
                "prot_family": obj.get("prot_family"),
                "substrate_pul": obj.get("substrate_pul"),
                "substrate_sub": obj.get("substrate_sub"),
            }
        )
        return _obj
