# coding: utf-8

"""
ME TT DataPortal Data Portal API

ME TT DataPortal Data Portal APIs to fetch Gut Microbes Genomes / Genes information.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class GeneBgcAnnotationSchema(BaseModel):
    """
    Biosynthetic gene cluster annotations.
    """  # noqa: E501

    gecco_bgc_type: Optional[StrictStr] = None
    nearest_mibig: Optional[StrictStr] = None
    nearest_mibig_class: Optional[StrictStr] = None
    antismash_bgc_function: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "gecco_bgc_type",
        "nearest_mibig",
        "nearest_mibig_class",
        "antismash_bgc_function",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneBgcAnnotationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if gecco_bgc_type (nullable) is None
        # and model_fields_set contains the field
        if self.gecco_bgc_type is None and "gecco_bgc_type" in self.model_fields_set:
            _dict["gecco_bgc_type"] = None

        # set to None if nearest_mibig (nullable) is None
        # and model_fields_set contains the field
        if self.nearest_mibig is None and "nearest_mibig" in self.model_fields_set:
            _dict["nearest_mibig"] = None

        # set to None if nearest_mibig_class (nullable) is None
        # and model_fields_set contains the field
        if (
            self.nearest_mibig_class is None
            and "nearest_mibig_class" in self.model_fields_set
        ):
            _dict["nearest_mibig_class"] = None

        # set to None if antismash_bgc_function (nullable) is None
        # and model_fields_set contains the field
        if (
            self.antismash_bgc_function is None
            and "antismash_bgc_function" in self.model_fields_set
        ):
            _dict["antismash_bgc_function"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneBgcAnnotationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "gecco_bgc_type": obj.get("gecco_bgc_type"),
                "nearest_mibig": obj.get("nearest_mibig"),
                "nearest_mibig_class": obj.get("nearest_mibig_class"),
                "antismash_bgc_function": obj.get("antismash_bgc_function"),
            }
        )
        return _obj
