# coding: utf-8

"""
ME TT DataPortal Data Portal API

ME TT DataPortal Data Portal APIs to fetch Gut Microbes Genomes / Genes information.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self


class OrthologBatchQuerySchema(BaseModel):
    """
    Schema for batch ortholog query parameters.
    """  # noqa: E501

    locus_tags: Optional[StrictStr] = None
    species_acronym: Optional[StrictStr] = None
    orthology_type: Optional[StrictStr] = None
    one_to_one_only: Optional[StrictBool] = Field(
        default=False, description="Return only one-to-one orthologs"
    )
    cross_species_only: Optional[StrictBool] = Field(
        default=False,
        description="Return only cross-species orthologs (exclude same species)",
    )
    max_results_per_gene: Optional[Annotated[int, Field(le=10000, strict=True)]] = (
        Field(default=100, description="Maximum number of orthologs per gene")
    )
    __properties: ClassVar[List[str]] = [
        "locus_tags",
        "species_acronym",
        "orthology_type",
        "one_to_one_only",
        "cross_species_only",
        "max_results_per_gene",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrthologBatchQuerySchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if locus_tags (nullable) is None
        # and model_fields_set contains the field
        if self.locus_tags is None and "locus_tags" in self.model_fields_set:
            _dict["locus_tags"] = None

        # set to None if species_acronym (nullable) is None
        # and model_fields_set contains the field
        if self.species_acronym is None and "species_acronym" in self.model_fields_set:
            _dict["species_acronym"] = None

        # set to None if orthology_type (nullable) is None
        # and model_fields_set contains the field
        if self.orthology_type is None and "orthology_type" in self.model_fields_set:
            _dict["orthology_type"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrthologBatchQuerySchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "locus_tags": obj.get("locus_tags"),
                "species_acronym": obj.get("species_acronym"),
                "orthology_type": obj.get("orthology_type"),
                "one_to_one_only": obj.get("one_to_one_only")
                if obj.get("one_to_one_only") is not None
                else False,
                "cross_species_only": obj.get("cross_species_only")
                if obj.get("cross_species_only") is not None
                else False,
                "max_results_per_gene": obj.get("max_results_per_gene")
                if obj.get("max_results_per_gene") is not None
                else 100,
            }
        )
        return _obj
