# coding: utf-8

"""
ME TT DataPortal Data Portal API

ME TT DataPortal Data Portal APIs to fetch Gut Microbes Genomes / Genes information.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Set
from typing_extensions import Self


class PPIInteractionSchema(BaseModel):
    """
    Schema for a single PPI interaction.
    """  # noqa: E501

    pair_id: StrictStr
    species_scientific_name: Optional[StrictStr] = None
    species_acronym: Optional[StrictStr] = None
    isolate_name: Optional[StrictStr] = None
    protein_a: StrictStr
    protein_b: StrictStr
    participants: List[StrictStr]
    participants_locus_tag: Optional[List[StrictStr]] = None
    is_self_interaction: Optional[StrictBool] = False
    protein_a_locus_tag: Optional[StrictStr] = None
    protein_a_uniprot_id: Optional[StrictStr] = None
    protein_a_name: Optional[StrictStr] = None
    protein_a_product: Optional[StrictStr] = None
    protein_b_locus_tag: Optional[StrictStr] = None
    protein_b_uniprot_id: Optional[StrictStr] = None
    protein_b_name: Optional[StrictStr] = None
    protein_b_product: Optional[StrictStr] = None
    string_protein_a_id: Optional[StrictStr] = None
    string_protein_b_id: Optional[StrictStr] = None
    consensus_score: Optional[Union[StrictFloat, StrictInt]] = None
    consensus_rank: Optional[StrictInt] = None
    consensus_avg_rank: Optional[Union[StrictFloat, StrictInt]] = None
    edge_id: Optional[StrictStr] = None
    interaction_weight: Optional[Union[StrictFloat, StrictInt]] = None
    n_sources: Optional[StrictInt] = None
    weight_coexp: Optional[Union[StrictFloat, StrictInt]] = None
    weight_operons_annogesic: Optional[Union[StrictFloat, StrictInt]] = None
    weight_operons_opdetect: Optional[Union[StrictFloat, StrictInt]] = None
    weight_operons_opmapper: Optional[Union[StrictFloat, StrictInt]] = None
    weight_phenocorr_neg: Optional[Union[StrictFloat, StrictInt]] = None
    weight_phenocorr_pos: Optional[Union[StrictFloat, StrictInt]] = None
    weight_pmi_gsms: Optional[Union[StrictFloat, StrictInt]] = None
    weight_pmi: Optional[Union[StrictFloat, StrictInt]] = None
    weight_ppi_gp_score_neg: Optional[Union[StrictFloat, StrictInt]] = None
    weight_ppi_gp_score_pos: Optional[Union[StrictFloat, StrictInt]] = None
    weight_ppi_perturb_score_neg: Optional[Union[StrictFloat, StrictInt]] = None
    weight_ppi_perturb_score_pos: Optional[Union[StrictFloat, StrictInt]] = None
    weight_ppi_xlms_files: Optional[Union[StrictFloat, StrictInt]] = None
    weight_ppi_xlms_peptides: Optional[Union[StrictFloat, StrictInt]] = None
    dl_score: Optional[Union[StrictFloat, StrictInt]] = None
    comelt_score: Optional[Union[StrictFloat, StrictInt]] = None
    perturbation_score: Optional[Union[StrictFloat, StrictInt]] = None
    abundance_score: Optional[Union[StrictFloat, StrictInt]] = None
    melt_score: Optional[Union[StrictFloat, StrictInt]] = None
    secondary_score: Optional[Union[StrictFloat, StrictInt]] = None
    bayesian_score: Optional[Union[StrictFloat, StrictInt]] = None
    string_score: Optional[Union[StrictFloat, StrictInt]] = None
    operon_score: Optional[Union[StrictFloat, StrictInt]] = None
    ecocyc_score: Optional[Union[StrictFloat, StrictInt]] = None
    tt_score: Optional[Union[StrictFloat, StrictInt]] = None
    ds_score: Optional[Union[StrictFloat, StrictInt]] = None
    has_xlms: Optional[StrictBool] = False
    has_string: Optional[StrictBool] = False
    has_operon: Optional[StrictBool] = False
    has_ecocyc: Optional[StrictBool] = False
    evidence_count: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = [
        "pair_id",
        "species_scientific_name",
        "species_acronym",
        "isolate_name",
        "protein_a",
        "protein_b",
        "participants",
        "participants_locus_tag",
        "is_self_interaction",
        "protein_a_locus_tag",
        "protein_a_uniprot_id",
        "protein_a_name",
        "protein_a_product",
        "protein_b_locus_tag",
        "protein_b_uniprot_id",
        "protein_b_name",
        "protein_b_product",
        "string_protein_a_id",
        "string_protein_b_id",
        "consensus_score",
        "consensus_rank",
        "consensus_avg_rank",
        "edge_id",
        "interaction_weight",
        "n_sources",
        "weight_coexp",
        "weight_operons_annogesic",
        "weight_operons_opdetect",
        "weight_operons_opmapper",
        "weight_phenocorr_neg",
        "weight_phenocorr_pos",
        "weight_pmi_gsms",
        "weight_pmi",
        "weight_ppi_gp_score_neg",
        "weight_ppi_gp_score_pos",
        "weight_ppi_perturb_score_neg",
        "weight_ppi_perturb_score_pos",
        "weight_ppi_xlms_files",
        "weight_ppi_xlms_peptides",
        "dl_score",
        "comelt_score",
        "perturbation_score",
        "abundance_score",
        "melt_score",
        "secondary_score",
        "bayesian_score",
        "string_score",
        "operon_score",
        "ecocyc_score",
        "tt_score",
        "ds_score",
        "has_xlms",
        "has_string",
        "has_operon",
        "has_ecocyc",
        "evidence_count",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PPIInteractionSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if species_scientific_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.species_scientific_name is None
            and "species_scientific_name" in self.model_fields_set
        ):
            _dict["species_scientific_name"] = None

        # set to None if species_acronym (nullable) is None
        # and model_fields_set contains the field
        if self.species_acronym is None and "species_acronym" in self.model_fields_set:
            _dict["species_acronym"] = None

        # set to None if isolate_name (nullable) is None
        # and model_fields_set contains the field
        if self.isolate_name is None and "isolate_name" in self.model_fields_set:
            _dict["isolate_name"] = None

        # set to None if participants_locus_tag (nullable) is None
        # and model_fields_set contains the field
        if (
            self.participants_locus_tag is None
            and "participants_locus_tag" in self.model_fields_set
        ):
            _dict["participants_locus_tag"] = None

        # set to None if protein_a_locus_tag (nullable) is None
        # and model_fields_set contains the field
        if (
            self.protein_a_locus_tag is None
            and "protein_a_locus_tag" in self.model_fields_set
        ):
            _dict["protein_a_locus_tag"] = None

        # set to None if protein_a_uniprot_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.protein_a_uniprot_id is None
            and "protein_a_uniprot_id" in self.model_fields_set
        ):
            _dict["protein_a_uniprot_id"] = None

        # set to None if protein_a_name (nullable) is None
        # and model_fields_set contains the field
        if self.protein_a_name is None and "protein_a_name" in self.model_fields_set:
            _dict["protein_a_name"] = None

        # set to None if protein_a_product (nullable) is None
        # and model_fields_set contains the field
        if (
            self.protein_a_product is None
            and "protein_a_product" in self.model_fields_set
        ):
            _dict["protein_a_product"] = None

        # set to None if protein_b_locus_tag (nullable) is None
        # and model_fields_set contains the field
        if (
            self.protein_b_locus_tag is None
            and "protein_b_locus_tag" in self.model_fields_set
        ):
            _dict["protein_b_locus_tag"] = None

        # set to None if protein_b_uniprot_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.protein_b_uniprot_id is None
            and "protein_b_uniprot_id" in self.model_fields_set
        ):
            _dict["protein_b_uniprot_id"] = None

        # set to None if protein_b_name (nullable) is None
        # and model_fields_set contains the field
        if self.protein_b_name is None and "protein_b_name" in self.model_fields_set:
            _dict["protein_b_name"] = None

        # set to None if protein_b_product (nullable) is None
        # and model_fields_set contains the field
        if (
            self.protein_b_product is None
            and "protein_b_product" in self.model_fields_set
        ):
            _dict["protein_b_product"] = None

        # set to None if string_protein_a_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.string_protein_a_id is None
            and "string_protein_a_id" in self.model_fields_set
        ):
            _dict["string_protein_a_id"] = None

        # set to None if string_protein_b_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.string_protein_b_id is None
            and "string_protein_b_id" in self.model_fields_set
        ):
            _dict["string_protein_b_id"] = None

        # set to None if consensus_score (nullable) is None
        # and model_fields_set contains the field
        if self.consensus_score is None and "consensus_score" in self.model_fields_set:
            _dict["consensus_score"] = None

        # set to None if consensus_rank (nullable) is None
        # and model_fields_set contains the field
        if self.consensus_rank is None and "consensus_rank" in self.model_fields_set:
            _dict["consensus_rank"] = None

        # set to None if consensus_avg_rank (nullable) is None
        # and model_fields_set contains the field
        if (
            self.consensus_avg_rank is None
            and "consensus_avg_rank" in self.model_fields_set
        ):
            _dict["consensus_avg_rank"] = None

        # set to None if edge_id (nullable) is None
        # and model_fields_set contains the field
        if self.edge_id is None and "edge_id" in self.model_fields_set:
            _dict["edge_id"] = None

        # set to None if interaction_weight (nullable) is None
        # and model_fields_set contains the field
        if (
            self.interaction_weight is None
            and "interaction_weight" in self.model_fields_set
        ):
            _dict["interaction_weight"] = None

        # set to None if n_sources (nullable) is None
        # and model_fields_set contains the field
        if self.n_sources is None and "n_sources" in self.model_fields_set:
            _dict["n_sources"] = None

        # set to None if weight_coexp (nullable) is None
        # and model_fields_set contains the field
        if self.weight_coexp is None and "weight_coexp" in self.model_fields_set:
            _dict["weight_coexp"] = None

        # set to None if weight_operons_annogesic (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_operons_annogesic is None
            and "weight_operons_annogesic" in self.model_fields_set
        ):
            _dict["weight_operons_annogesic"] = None

        # set to None if weight_operons_opdetect (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_operons_opdetect is None
            and "weight_operons_opdetect" in self.model_fields_set
        ):
            _dict["weight_operons_opdetect"] = None

        # set to None if weight_operons_opmapper (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_operons_opmapper is None
            and "weight_operons_opmapper" in self.model_fields_set
        ):
            _dict["weight_operons_opmapper"] = None

        # set to None if weight_phenocorr_neg (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_phenocorr_neg is None
            and "weight_phenocorr_neg" in self.model_fields_set
        ):
            _dict["weight_phenocorr_neg"] = None

        # set to None if weight_phenocorr_pos (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_phenocorr_pos is None
            and "weight_phenocorr_pos" in self.model_fields_set
        ):
            _dict["weight_phenocorr_pos"] = None

        # set to None if weight_pmi_gsms (nullable) is None
        # and model_fields_set contains the field
        if self.weight_pmi_gsms is None and "weight_pmi_gsms" in self.model_fields_set:
            _dict["weight_pmi_gsms"] = None

        # set to None if weight_pmi (nullable) is None
        # and model_fields_set contains the field
        if self.weight_pmi is None and "weight_pmi" in self.model_fields_set:
            _dict["weight_pmi"] = None

        # set to None if weight_ppi_gp_score_neg (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_ppi_gp_score_neg is None
            and "weight_ppi_gp_score_neg" in self.model_fields_set
        ):
            _dict["weight_ppi_gp_score_neg"] = None

        # set to None if weight_ppi_gp_score_pos (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_ppi_gp_score_pos is None
            and "weight_ppi_gp_score_pos" in self.model_fields_set
        ):
            _dict["weight_ppi_gp_score_pos"] = None

        # set to None if weight_ppi_perturb_score_neg (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_ppi_perturb_score_neg is None
            and "weight_ppi_perturb_score_neg" in self.model_fields_set
        ):
            _dict["weight_ppi_perturb_score_neg"] = None

        # set to None if weight_ppi_perturb_score_pos (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_ppi_perturb_score_pos is None
            and "weight_ppi_perturb_score_pos" in self.model_fields_set
        ):
            _dict["weight_ppi_perturb_score_pos"] = None

        # set to None if weight_ppi_xlms_files (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_ppi_xlms_files is None
            and "weight_ppi_xlms_files" in self.model_fields_set
        ):
            _dict["weight_ppi_xlms_files"] = None

        # set to None if weight_ppi_xlms_peptides (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_ppi_xlms_peptides is None
            and "weight_ppi_xlms_peptides" in self.model_fields_set
        ):
            _dict["weight_ppi_xlms_peptides"] = None

        # set to None if dl_score (nullable) is None
        # and model_fields_set contains the field
        if self.dl_score is None and "dl_score" in self.model_fields_set:
            _dict["dl_score"] = None

        # set to None if comelt_score (nullable) is None
        # and model_fields_set contains the field
        if self.comelt_score is None and "comelt_score" in self.model_fields_set:
            _dict["comelt_score"] = None

        # set to None if perturbation_score (nullable) is None
        # and model_fields_set contains the field
        if (
            self.perturbation_score is None
            and "perturbation_score" in self.model_fields_set
        ):
            _dict["perturbation_score"] = None

        # set to None if abundance_score (nullable) is None
        # and model_fields_set contains the field
        if self.abundance_score is None and "abundance_score" in self.model_fields_set:
            _dict["abundance_score"] = None

        # set to None if melt_score (nullable) is None
        # and model_fields_set contains the field
        if self.melt_score is None and "melt_score" in self.model_fields_set:
            _dict["melt_score"] = None

        # set to None if secondary_score (nullable) is None
        # and model_fields_set contains the field
        if self.secondary_score is None and "secondary_score" in self.model_fields_set:
            _dict["secondary_score"] = None

        # set to None if bayesian_score (nullable) is None
        # and model_fields_set contains the field
        if self.bayesian_score is None and "bayesian_score" in self.model_fields_set:
            _dict["bayesian_score"] = None

        # set to None if string_score (nullable) is None
        # and model_fields_set contains the field
        if self.string_score is None and "string_score" in self.model_fields_set:
            _dict["string_score"] = None

        # set to None if operon_score (nullable) is None
        # and model_fields_set contains the field
        if self.operon_score is None and "operon_score" in self.model_fields_set:
            _dict["operon_score"] = None

        # set to None if ecocyc_score (nullable) is None
        # and model_fields_set contains the field
        if self.ecocyc_score is None and "ecocyc_score" in self.model_fields_set:
            _dict["ecocyc_score"] = None

        # set to None if tt_score (nullable) is None
        # and model_fields_set contains the field
        if self.tt_score is None and "tt_score" in self.model_fields_set:
            _dict["tt_score"] = None

        # set to None if ds_score (nullable) is None
        # and model_fields_set contains the field
        if self.ds_score is None and "ds_score" in self.model_fields_set:
            _dict["ds_score"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PPIInteractionSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "pair_id": obj.get("pair_id"),
                "species_scientific_name": obj.get("species_scientific_name"),
                "species_acronym": obj.get("species_acronym"),
                "isolate_name": obj.get("isolate_name"),
                "protein_a": obj.get("protein_a"),
                "protein_b": obj.get("protein_b"),
                "participants": obj.get("participants"),
                "participants_locus_tag": obj.get("participants_locus_tag"),
                "is_self_interaction": obj.get("is_self_interaction")
                if obj.get("is_self_interaction") is not None
                else False,
                "protein_a_locus_tag": obj.get("protein_a_locus_tag"),
                "protein_a_uniprot_id": obj.get("protein_a_uniprot_id"),
                "protein_a_name": obj.get("protein_a_name"),
                "protein_a_product": obj.get("protein_a_product"),
                "protein_b_locus_tag": obj.get("protein_b_locus_tag"),
                "protein_b_uniprot_id": obj.get("protein_b_uniprot_id"),
                "protein_b_name": obj.get("protein_b_name"),
                "protein_b_product": obj.get("protein_b_product"),
                "string_protein_a_id": obj.get("string_protein_a_id"),
                "string_protein_b_id": obj.get("string_protein_b_id"),
                "consensus_score": obj.get("consensus_score"),
                "consensus_rank": obj.get("consensus_rank"),
                "consensus_avg_rank": obj.get("consensus_avg_rank"),
                "edge_id": obj.get("edge_id"),
                "interaction_weight": obj.get("interaction_weight"),
                "n_sources": obj.get("n_sources"),
                "weight_coexp": obj.get("weight_coexp"),
                "weight_operons_annogesic": obj.get("weight_operons_annogesic"),
                "weight_operons_opdetect": obj.get("weight_operons_opdetect"),
                "weight_operons_opmapper": obj.get("weight_operons_opmapper"),
                "weight_phenocorr_neg": obj.get("weight_phenocorr_neg"),
                "weight_phenocorr_pos": obj.get("weight_phenocorr_pos"),
                "weight_pmi_gsms": obj.get("weight_pmi_gsms"),
                "weight_pmi": obj.get("weight_pmi"),
                "weight_ppi_gp_score_neg": obj.get("weight_ppi_gp_score_neg"),
                "weight_ppi_gp_score_pos": obj.get("weight_ppi_gp_score_pos"),
                "weight_ppi_perturb_score_neg": obj.get("weight_ppi_perturb_score_neg"),
                "weight_ppi_perturb_score_pos": obj.get("weight_ppi_perturb_score_pos"),
                "weight_ppi_xlms_files": obj.get("weight_ppi_xlms_files"),
                "weight_ppi_xlms_peptides": obj.get("weight_ppi_xlms_peptides"),
                "dl_score": obj.get("dl_score"),
                "comelt_score": obj.get("comelt_score"),
                "perturbation_score": obj.get("perturbation_score"),
                "abundance_score": obj.get("abundance_score"),
                "melt_score": obj.get("melt_score"),
                "secondary_score": obj.get("secondary_score"),
                "bayesian_score": obj.get("bayesian_score"),
                "string_score": obj.get("string_score"),
                "operon_score": obj.get("operon_score"),
                "ecocyc_score": obj.get("ecocyc_score"),
                "tt_score": obj.get("tt_score"),
                "ds_score": obj.get("ds_score"),
                "has_xlms": obj.get("has_xlms")
                if obj.get("has_xlms") is not None
                else False,
                "has_string": obj.get("has_string")
                if obj.get("has_string") is not None
                else False,
                "has_operon": obj.get("has_operon")
                if obj.get("has_operon") is not None
                else False,
                "has_ecocyc": obj.get("has_ecocyc")
                if obj.get("has_ecocyc") is not None
                else False,
                "evidence_count": obj.get("evidence_count")
                if obj.get("evidence_count") is not None
                else 0,
            }
        )
        return _obj
