# coding: utf-8

"""
ME TT DataPortal Data Portal API

ME TT DataPortal Data Portal APIs to fetch Gut Microbes Genomes / Genes information.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class StrainAnnotationSchema(BaseModel):
    """
    StrainAnnotationSchema
    """  # noqa: E501

    pipeline: Optional[StrictStr] = None
    pipeline_version: Optional[StrictStr] = None
    processing_reference: Optional[StrictStr] = None
    processing_document_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "pipeline",
        "pipeline_version",
        "processing_reference",
        "processing_document_url",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StrainAnnotationSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pipeline (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline is None and "pipeline" in self.model_fields_set:
            _dict["pipeline"] = None

        # set to None if pipeline_version (nullable) is None
        # and model_fields_set contains the field
        if (
            self.pipeline_version is None
            and "pipeline_version" in self.model_fields_set
        ):
            _dict["pipeline_version"] = None

        # set to None if processing_reference (nullable) is None
        # and model_fields_set contains the field
        if (
            self.processing_reference is None
            and "processing_reference" in self.model_fields_set
        ):
            _dict["processing_reference"] = None

        # set to None if processing_document_url (nullable) is None
        # and model_fields_set contains the field
        if (
            self.processing_document_url is None
            and "processing_document_url" in self.model_fields_set
        ):
            _dict["processing_document_url"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StrainAnnotationSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "pipeline": obj.get("pipeline"),
                "pipeline_version": obj.get("pipeline_version"),
                "processing_reference": obj.get("processing_reference"),
                "processing_document_url": obj.get("processing_document_url"),
            }
        )
        return _obj
